name: NGT Case Monitor (AI Vision)

on:
  schedule:
    - cron: "30 3 * * *"   # 09:00 IST daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      NGT_URL: "https://www.greentribunal.gov.in/caseDetails/PUNE/2704138000312025?page=order"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libtesseract-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run AI Vision watcher
        id: runwatch
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
        run: |
          python ngt_watch_openai.py
          cat result.json
          STATUS=$(jq -r '.status' result.json)
          MESSAGE=$(jq -r '.message // ""' result.json)
          CASE_STATUS=$(jq -r '.case_status // ""' result.json)
          NEXT_HEARING=$(jq -r '.next_hearing_date // ""' result.json)
          ORDER_SUMMARY=$(jq -r '.order_summary // ""' result.json)
          REMARKS=$(jq -r '.remarks // ""' result.json)
          {
            echo "status=$STATUS"
            printf 'message<<EOF\n%s\nEOF\n' "$MESSAGE"
            printf 'case_status<<EOF\n%s\nEOF\n' "$CASE_STATUS"
            printf 'next_hearing_date<<EOF\n%s\nEOF\n' "$NEXT_HEARING"
            printf 'order_summary<<EOF\n%s\nEOF\n' "$ORDER_SUMMARY"
            printf 'remarks<<EOF\n%s\nEOF\n' "$REMARKS"
          } >> "$GITHUB_OUTPUT"

      - name: Commit state if changed
        if: steps.runwatch.outputs.status == 'changed'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .state/last_hash.txt
          git commit -m "chore(state): update last_hash [skip ci]" || echo "No changes to commit"
          git push

      - name: Upload screenshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ngt-monitor-artifacts
          path: |
            page.png
            result.json

      - name: Send Email (on change or error)
        if: steps.runwatch.outputs.status != 'ok'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_EMAIL }}
          subject: "NGT Case Update - ${{ steps.runwatch.outputs.status }}"
          body: |
            Case URL: ${{ env.NGT_URL }}
            Message: ${{ steps.runwatch.outputs.message }}
            Case Status: ${{ steps.runwatch.outputs.case_status }}
            Next Hearing: ${{ steps.runwatch.outputs.next_hearing_date }}
            Summary: ${{ steps.runwatch.outputs.order_summary }}
            Remarks: ${{ steps.runwatch.outputs.remarks }}
          secure: ${{ secrets.SMTP_PORT == '465' }}
